### ISSUE TITLE
eyes needs to be added to package.json

### ISSUE THREAD

**Issue by dcbartlett** [Marak/session.js#11]
module.js:340
    throw err;
          ^
Error: Cannot find module 'eyes'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/dennis/Projects/CompareMetrics/sora/node_modules/sesh/lib/core.js:4:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by scherler** [comment]
it is fixed in the trunk https://github.com/Marak/session.js/commit/20ed2a7d5caf07fa98f75f337ece48459568abe6
